import styles from './Header.module.css'
const Header = () => {
  return (
    <div className = {styles.header}>
      {/* class="_header_s6du5_1" (shown as classname on inspecting the header div, used for encapsulating the data) is generated by css module, it is unique and it is used to apply styles to the component. */}
      <h3>Shreyians</h3>
      <button className ={styles.btn}>Login</button>
    </div>
  )
}

export default Header
